name: Deploy Mental Health Chatbot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: SSH into EC2 and Deploy
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        timeout: 25m
        script: |
          cd "/home/ubuntu/MindEase/Sentiment analysis project"
          git pull origin main
          docker build -t chatbot-app .
          docker stop chatbot || true
          docker rm chatbot || true
          docker run -d -p 80:8000 --name chatbot chatbot-app
